name: pqcoin-core # you probably want to 'snapcraft register <name>'
version: '1.14.5'
summary: Reference client of Pqcoin, a peer-to-peer digital currency like Bitcoin.
description: |
  Pqcoin is a cryptocurrency like Bitcoin, although it does not use SHA256 as its proof of work (POW). Taking development cues from Tenebrix and Litecoin, Pqcoin currently employs a simplified variant of scrypt. MIT licenced.

base: core18
grade: stable
confinement: strict
architectures:
  - build-on: [amd64, i386, arm64]

apps:
  d:
    command: pqcoind
    plugs: [home, removable-media, network, network-bind]
    environment:
    # Override HOME so the datadir is located at ~/snap/pqcoin-core/common/.pqcoin/ instead of ~/snap/pqcoin-core/current/.pqcoin/, and each new version of the snap won't have a different data directory: https://docs.snapcraft.io/environment-variables/7983
      HOME: $SNAP_USER_COMMON
  qt:
    command: qt4-launch pqcoin-qt
    plugs: [home, removable-media, network, network-bind, desktop, x11, unity7]
    environment:
      HOME: $SNAP_USER_COMMON
      DISABLE_WAYLAND: 1
  cli:
    command: pqcoin-cli
    plugs: [home, removable-media, network]
    environment:
      HOME: $SNAP_USER_COMMON

parts:
  pqcoin-core:
    plugin: nil
    override-build: |
      echo "Downloading files..."
      wget https://github.com/pqcoin/pqcoin/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/pqcoin-${SNAPCRAFT_PROJECT_VERSION}-${SNAPCRAFT_ARCH_TRIPLET}.tar.gz
      wget https://github.com/pqcoin/gitian.sigs/archive/refs/heads/master.zip
      unzip master.zip
      echo "Verifying secure hash matches signed values..."
      checksum=$(sha256sum pqcoin-${SNAPCRAFT_PROJECT_VERSION}-${SNAPCRAFT_ARCH_TRIPLET}.tar.gz)
      if ! (grep -r $checksum * | grep pqcoin-${SNAPCRAFT_PROJECT_VERSION}-${SNAPCRAFT_ARCH_TRIPLET}.tar.gz); then
        echo "Secure hash not verified."
        return
      else
        echo "Secure hash verified."
      fi
      tar -xvf pqcoin-${SNAPCRAFT_PROJECT_VERSION}-${SNAPCRAFT_ARCH_TRIPLET}.tar.gz
      echo "Running tests..."
      if ! (pqcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/test_pqcoin); then
        echo "Pqcoin tests failed."
        return
      else
        echo "Pqcoin tests passed."
      fi
      echo "Installing Pqcoin..."
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin pqcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/pqcoind
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin pqcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/pqcoin-qt
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin pqcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/pqcoin-cli
      wget https://raw.githubusercontent.com/pqcoin/pqcoin/master/share/pixmaps/pqcoin128.png
      install -m 0644 -D -t $SNAPCRAFT_PART_INSTALL/share/pixmaps pqcoin128.png
    build-packages:
      - unzip
      - wget
    stage-packages:
      - libfreetype6
      - libpng16-16
      - libx11-xcb1
      - libx11-6
      - libfontconfig
  qt4conf:
    build-packages:
      - dpkg-dev
    plugin: make
    source: https://github.com/kyrofa/qt4conf.git
